DEFAULT_BLOCKS_ARGS = {
    'efficientnetv2-s': [
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 24,
            'out_channels': 24,
            'expand_ratio': 1,
            'se_ratio': 0.0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 4,
            'in_channels': 24,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0.0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'conv_type': 1,
            'expand_ratio': 4,
            'in_channels': 48,
            'kernel_size': 3,
            'num_repeat': 4,
            'out_channels': 64,
            'se_ratio': 0,
            'stride': 2,
            'pool': None
        },
        {
            'conv_type': 0,
            'expand_ratio': 4,
            'in_channels': 64,
            'kernel_size': 3,
            'num_repeat': 6,
            'out_channels': 128,
            'se_ratio': 0.25,
            'stride': 2,
            'pool': None
        },
        {
            'conv_type': 0,
            'expand_ratio': 6,
            'in_channels': 128,
            'kernel_size': 3,
            'num_repeat': 9,
            'out_channels': 160,
            'se_ratio': 0.25,
            'stride': 1,
            'pool': None
        },
        {
            'conv_type': 0,
            'expand_ratio': 6,
            'in_channels': 160,
            'kernel_size': 3,
            'num_repeat': 15,
            'out_channels': 256,
            'se_ratio': 0.25,
            'stride': 2,
            'pool': None
        },
    ],
    'efficientnetv2-m': [
        {
            'kernel_size': 3,
            'num_repeat': 3,
            'in_channels': 24,
            'out_channels': 24,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 24,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 48,
            'out_channels': 80,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 7,
            'in_channels': 80,
            'out_channels': 160,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 14,
            'in_channels': 160,
            'out_channels': 176,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 18,
            'in_channels': 176,
            'out_channels': 304,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 304,
            'out_channels': 512,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
    ],
    'efficientnetv2-l': [
        {
            'kernel_size': 3,
            'num_repeat': 4,
            'in_channels': 32,
            'out_channels': 32,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 7,
            'in_channels': 32,
            'out_channels': 64,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 7,
            'in_channels': 64,
            'out_channels': 96,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 10,
            'in_channels': 96,
            'out_channels': 192,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 19,
            'in_channels': 192,
            'out_channels': 224,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 25,
            'in_channels': 224,
            'out_channels': 384,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 7,
            'in_channels': 384,
            'out_channels': 640,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
    ],
    'efficientnetv2-b0': [
        {
            'kernel_size': 3,
            'num_repeat': 1,
            'in_channels': 32,
            'out_channels': 16,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 16,
            'out_channels': 32,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 32,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 3,
            'in_channels': 48,
            'out_channels': 96,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 96,
            'out_channels': 112,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 8,
            'in_channels': 112,
            'out_channels': 192,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
    ],
    'efficientnetv2-b1': [
        {
            'kernel_size': 3,
            'num_repeat': 1,
            'in_channels': 32,
            'out_channels': 16,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 16,
            'out_channels': 32,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 32,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 3,
            'in_channels': 48,
            'out_channels': 96,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 96,
            'out_channels': 112,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 8,
            'in_channels': 112,
            'out_channels': 192,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
    ],
    'efficientnetv2-b2': [
        {
            'kernel_size': 3,
            'num_repeat': 1,
            'in_channels': 32,
            'out_channels': 16,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 16,
            'out_channels': 32,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 32,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 3,
            'in_channels': 48,
            'out_channels': 96,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 96,
            'out_channels': 112,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 8,
            'in_channels': 112,
            'out_channels': 192,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
    ],
    'efficientnetv2-b3': [
        {
            'kernel_size': 3,
            'num_repeat': 1,
            'in_channels': 32,
            'out_channels': 16,
            'expand_ratio': 1,
            'se_ratio': 0,
            'stride': 1,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 16,
            'out_channels': 32,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 2,
            'in_channels': 32,
            'out_channels': 48,
            'expand_ratio': 4,
            'se_ratio': 0,
            'stride': 2,
            'conv_type': 1,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 3,
            'in_channels': 48,
            'out_channels': 96,
            'expand_ratio': 4,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 5,
            'in_channels': 96,
            'out_channels': 112,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 1,
            'conv_type': 0,
            'pool': None
        },
        {
            'kernel_size': 3,
            'num_repeat': 8,
            'in_channels': 112,
            'out_channels': 192,
            'expand_ratio': 6,
            'se_ratio': 0.25,
            'stride': 2,
            'conv_type': 0,
            'pool': None
        },
    ],
}
